/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    id("java")
    id("io.ktor.plugin") version "2.2.3"
}

application {
    mainClass.set("com.mangust.Lab7")
}

repositories {
    mavenCentral()
}

dependencies {
  implementation("com.google.code.gson:gson:2.10.1")
}

ktor {
    fatJar {
        archiveFileName.set("fat.jar")
    }
}
